language: swift

osx_image: xcode11.2.1
script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project SinzuMoney.xcodeproj -scheme SinzuMoney -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=12.1,name=iPhoneX ONLY_ACTIVE_ARCH=YES
