language: swift

osx_image: xcode11.2
env:
  matrix:
    - TEST_SDK=iphonesimulator13.2 OS=13.2.2 NAME='iPhone 11 Pro'

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project SinzuMoney.xcodeproj -scheme SinzuMoney -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES build test

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'SinzuMoney'
